server:
  port: 8300
spring:
  application:
    name: delivery-service
  config:
    activate:
      on-profile: local, dev, local
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
endpoint:
  order-service: http://localhost:8900